<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log inForgotten password</name>
   <tag></tag>
   <elementGuidId>8f781675-5e0a-482b-a5c0-b6485d01be9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginform</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginform']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>700944cc-4f4c-4e1f-922c-6de23e0c1169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginform</value>
      <webElementGuid>8d7acab7-f2f9-4dac-b69a-0823ab84e661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log inForgotten password?</value>
      <webElementGuid>38800050-1cea-40f8-84b4-0c7ae216dba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)</value>
      <webElementGuid>268a7f25-0407-4b2c-9a15-31e5432175c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='loginform']</value>
      <webElementGuid>555022cb-6b85-4638-a7c9-66115bf7992f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div[2]</value>
      <webElementGuid>a79af3a6-0abb-4aef-b7a8-d2be3bb1ac94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invalid username or password'])[1]/following::div[1]</value>
      <webElementGuid>8bdeee83-287a-45f2-ac4e-96905f137017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrong credentials'])[1]/following::div[2]</value>
      <webElementGuid>f86b0a50-ba4a-40dd-9bd8-c7c50a0743ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>96ba2992-16f7-421c-80e7-ed4d738b9e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'loginform' and (text() = 'Log inForgotten password?' or . = 'Log inForgotten password?')]</value>
      <webElementGuid>81dd59ee-0fd5-4bd0-add1-f4eb198ef7db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
